"""add payment fields to orders

Revision ID: 1968eaa18325
Revises: 881cea4684b8
Create Date: 2026-04-25 15:19:23.380371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1968eaa18325'
down_revision: Union[str, Sequence[str], None] = '881cea4684b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_status', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'stripe_payment_intent_id')
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###
